version: '3.3'

services:

  webdav:
    image: ugeek/webdav:amd64    
    container_name: webdav
    restart: unless-stopped
    volumes:
      - ./share:/media
    ports:
      - "8200:80" 
    env_file: .env          
    environment:
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000     
    networks:
      - caddy          
      
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - ./caddy_data:/data
      - ./caddy_config:/config
    networks:
      - caddy

networks:  
  caddy:    
